data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifiers.tomato]
    name = "tomato"
    public_key = "5EHFGME5cGrZHT3AQnzbwdc4Cy3catT7nUxDpzZqu3bcYxHV"

[[chains]]
  [chains.Joystream]
  name = "joystream"
  color = "#4038ff"
  verifier = "tomato"
  rpc_endpoints = [
    "wss://rpc.joystream.org"]
  testnet = false
  verifier = "tomato"
