public_dir = "public"
qr_dir = "public/qr"

[verifiers]
  [verifiers.tomato]
    name = "tomato"
    public_key = "5EHFGME5cGrZHT3AQnzbwdc4Cy3catT7nUxDpzZqu3bcYxHV"

[chains]
  [chains.Joystream]
  name = "joystream"
  color = "#4038ff"
  verifier = "tomato"
